name: Project - Reqular Checks
on:
  pull_request:
    branches:
      - main
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          make install
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make test
